export const TOGGLE_RYDES_TAB = 'TOGGLE_RYDES_TAB';
export const LIFT_CURRENT_PAGE_TO_STATE = 'LIFT_CURRENT_PAGE_TO_STATE';
export const LIFT_TOKEN_TO_STATE = 'LIFT_TOKEN_TO_STATE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const  LIFT_BIG_SEARCH = 'LIFT_BIG_SEARCH';
export const  LIFT_MINI_SEARCH = 'LIFT_MINI_SEARCH';
